### PR TITLE
Small issues

### PR DESCRIPTION
**Pull request by xpavlic**
- new configuration option ldap start_tls (boolean)
- perun_storage keystore and signing keystore configs now correcty contain paths to jwk files

### CODE REVIEW

**Comment by melanger** [comment]
@xpavlic Please edit commit messages so that they reference the issues they fix. I highly recommend [commitizen](https://github.com/commitizen/cz-cli).

**Review by melanger — CHANGES_REQUESTED** [review]
@xpavlic `Closes:` does not work, use `fix:` instead

**Comment by xpavlic** [comment]
"Closes: ...." should work as well. It is generated by npx git-cz as you can see on the screenshot. Also I already used it before.
image

**Comment by melanger** [comment]
> "Closes: ...." should work as well. It is generated by npx git-cz as you can see on the screenshot. Also I already used it before.

I still highly recommend commitizen (`npx cz`) instead of `npx git-cz`. From [here](https://github.com/gitbucket/gitbucket/wiki/How-to-Close-Reference-issues-and-pull-request) it seems that `closes #123` should work, so the problem is either in capital `C` or in the extra colon `:`. GitHub still shows no linked issues to this PR:

No linked issues yet

**Comment by xpavlic** [comment]
I already used git cz, but issues still did not link. I had to link them manually.

**Pull request merged**
