### PR TITLE
redesign (Bootstrap 5), override any template and some CSS classes

### PR DESCRIPTION
**Pull request by melanger**
* recreated dark design using Bootstrap 5
* compatible with MUNI CSS framework

### CODE REVIEW

**Comment by xpavlic** [comment]
Screenshot from 2021-08-17 21-14-40
On the registration page, I would move "register" button under input field, and also align all elements to center and add gap between each other. Also unify buttons width.

Screenshot from 2021-08-17 21-26-48
On the authentication page unify buttons width and add gap between them.

Screenshot from 2021-08-17 21-34-15
On the token management page, move register button under input field, also I prefer continue button either on the right side or under register button after it's move. Unify gap between Token management and tokens and between Register new token and input fileld. Unify size of all buttons.

On all pages make forms with buttons a little bit lighter, or remove border line, which is barely visible.

**Review by xpavlic — CHANGES_REQUESTED** [review]
Screenshot from 2021-08-17 21-14-40
On the registration page, I would move "register" button under input field, and also align all elements to center and add gap between each other. Also unify buttons width.

Screenshot from 2021-08-17 21-26-48
On the authentication page unify buttons width and add gap between them.

Screenshot from 2021-08-17 21-34-15
On the token management page, move register button under input field, also I prefer continue button either on the right side or under register button after it's move. Unify gap between Token management and tokens and between Register new token and input fileld. Unify size of all buttons.

On all pages make forms with buttons a little bit lighter, or remove border line, which is barely visible.

**Review by xpavlic — COMMENTED** [review]
image
Is it possible to unify buttons width same as it was in old style? Also resizing gaps between buttons to half would look better in my opinion. (Same for registration page)

**Comment by melanger** [comment]
> image
> Is it possible to unify buttons width same as it was in old style? Also resizing gaps between buttons to half would look better in my opinion. (Same for registration page)

Originally they were fixed width (200px) but now they are responsive to screen width and content. It is possible to make them full width (which is IMHO even worse) or use fixed width and allow text wrap or make the text shorter. Feel free to add a commit with your suggestion.

**Review by xpavlic — COMMENTED** [review]
Added commit with my suggestions. Style is now more unified and responsivity preserved.

**Review by melanger — COMMENTED** [review]
@xpavlic Please keep the "extra" elements and styles, they are there for compatibility with MUNI CSS framework, mostly `<p class="{{ style_classes['button_wrap'] }}">` and `div`s in `register_credential_form_items`

**Comment by melanger** [comment]
suggestions merged, thanks

**Pull request merged**
